### PR TITLE
Handle RareOrImpossibleDateException when evaluating crontabs

### PR DESCRIPTION
**Pull request by martinmcnulty**
Change `NextExecutionUtils` to handle the `RareOrImpossibleDateException` that can be thrown by [CronTab.ceil](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/scheduler/CronTab.java#L373). Ignore `CronTabs` that throw this exception, since they will not have any imminent next executions anyway. 

### Testing done

Tested a snapshot build in Jenkins and verified that

1. more "next executions" are listed
2. the RareOrImpossibleDateException no longer appears in the controller logs

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by jonesbusy** [comment]
Thanks for your contribution @martinmcnulty 

Give me some time to review it

**Comment by jonesbusy** [comment]
Can you ensure this PR/branch is rebased on 'main' ?

If not you will get build issue because of different Jenkinsfile

https://ci.jenkins.io/job/Plugins/job/next-executions-plugin/job/PR-55/2/console

```
11:50:23  Connecting to https://api.github.com/ to check permissions of obtain list of martinmcnulty for jenkinsci/next-executions-plugin
11:50:24  Loading trusted files from base branch main at 0a47a09840df8cf1661577707fe36b973e32d662 rather than 1e065d0b646dc933a6e2f7a24bb279c3647f683b
11:50:24  Obtained Jenkinsfile from 0a47a09840df8cf1661577707fe36b973e32d662
11:50:24  ‘Jenkinsfile’ has been modified in an untrusted revision
```

**Review by jonesbusy — CHANGES_REQUESTED** [review]
PR to rebase in order for build to run

**Comment by martinmcnulty** [comment]
Thanks for the quick response. Have rebased on main 👍

**Review by jonesbusy — APPROVED** [review]

**Comment by jonesbusy** [comment]
If you don't mind I will merge and release in ~1 week. This plugin doesn't have a lot of test coverage and I would like to also perform some interactive test to avoid regression.

Thanks again for the contribution.

**Comment by martinmcnulty** [comment]
No problem at all, whenever you're ready. Thanks for reviewing :)

**Pull request merged**
