### PR TITLE
Add tests to improve test coverage

### LINKED ISSUE #56: Missing test coverage
### What feature do you want to see added?

This plugin miss some essential testing to validate non-regression

Unit tests
HTMLUnit for UI configuration
Jenkins Configuration Test

More information on https://www.jenkins.io/doc/developer/testing/

### Upstream changes

_No response_

### PR DESCRIPTION
**Pull request by sridamul**
Related to #56 
Added tests to increase the test coverage. Still some functions require tests (commented as TODO), I will add it in few days.

#### Before
Screenshot 2024-03-19 234723

#### After
Screenshot 2024-03-19 234515

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by jonesbusy** [comment]
Thanks for tour PR! I will take a loot at this soon

**Comment by jonesbusy** [comment]
Apparently the main branch is faling. One test fail

@sridamul

**Comment by sridamul** [comment]
Hey @jonesbusy, could you please restart the build? Spotbugs appears to be working fine for me. I've tested it on both Windows and Linux.

**Comment by jonesbusy** [comment]
I don't think it's related to spotbugs.

There is only one test failing

java.lang.AssertionError: expected:<0> but was:<-1>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at hudson.plugins.nextexecutions.NextBuildsTest.testCompareToWithEqualDates(NextBuildsTest.java:73)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.jvnet.hudson.test.JenkinsRule$1.evaluate(JenkinsRule.java:656)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1583)

Do you think the test depends on some timezone or timing issue ?

**Comment by sridamul** [comment]
Yes. The test fail is due to different TimeZone in Calendar.getInstance()

**Pull request merged**
